# Generated by Django 4.2.2 on 2023-07-03 04:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=1000)),
                ('filename', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('downloads', models.IntegerField()),
                ('upload_date', models.DateField(default=datetime.datetime(2023, 7, 3, 4, 14, 44, 532110, tzinfo=datetime.timezone.utc))),
                ('abstract_num', models.IntegerField()),
                ('es_num', models.IntegerField()),
            ],
        ),
    ]
