# Generated by Django 4.2.2 on 2023-07-03 04:33

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='filename',
        ),
        migrations.AddField(
            model_name='books',
            name='files',
            field=models.FileField(default=1, upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'word', 'excel'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 4, 32, 53, 91956, tzinfo=datetime.timezone.utc)),
        ),
    ]
