# Generated by Django 4.1.7 on 2024-03-01 01:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscripts',
            name='accessionnum',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscripts',
            name='identifier',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 1, 1, 41, 37, 675771, tzinfo=datetime.timezone.utc)),
        ),
    ]
