# Generated by Django 4.2.2 on 2023-07-03 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_books_filename_books_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='files',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='books',
            name='downloads',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 4, 38, 34, 751962, tzinfo=datetime.timezone.utc)),
        ),
    ]
