# Generated by Django 4.2.2 on 2023-07-03 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_books_downloads_alter_books_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 3, 4, 45, 9, 781679, tzinfo=datetime.timezone.utc)),
        ),
    ]
