# Generated by Django 4.2.2 on 2023-07-04 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_books_category_alter_books_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='abstract_num',
            new_name='abstractES_num',
        ),
        migrations.RemoveField(
            model_name='books',
            name='es_num',
        ),
        migrations.AlterField(
            model_name='books',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 4, 6, 37, 32, 426917, tzinfo=datetime.timezone.utc)),
        ),
    ]
