# Generated by Django 4.2.3 on 2023-07-05 01:45

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rename_abstract_num_books_abstractes_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=1000)),
                ('filename', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'word', 'excel'])])),
                ('downloads', models.IntegerField()),
                ('year', models.CharField(max_length=250)),
                ('category', models.CharField(max_length=20)),
                ('upload_date', models.DateField(default=datetime.datetime(2023, 7, 5, 1, 45, 8, 339732, tzinfo=datetime.timezone.utc))),
                ('abstractES_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('requests_email', models.CharField(max_length=250)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
