# Generated by Django 4.2.3 on 2023-07-06 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_manuscripts_visitors_delete_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='requests_email',
            new_name='file_link',
        ),
        migrations.AddField(
            model_name='visitors',
            name='file_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitors',
            name='requests_email_token',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 1, 18, 44, 161844, tzinfo=datetime.timezone.utc)),
        ),
    ]
