# Generated by Django 4.2.3 on 2023-07-06 13:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_rename_requests_email_visitors_file_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='forget_password_token',
        ),
        migrations.RemoveField(
            model_name='librarian',
            name='user',
        ),
        migrations.AddField(
            model_name='librarian',
            name='password',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarian',
            name='username',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 13, 34, 7, 132542, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_password_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
