# Generated by Django 4.2.3 on 2023-07-06 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_librarian_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscripts',
            old_name='category',
            new_name='program',
        ),
        migrations.RenameField(
            model_name='staffs',
            old_name='user',
            new_name='credentials',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 6, 13, 44, 47, 338110, tzinfo=datetime.timezone.utc)),
        ),
    ]
