# Generated by Django 4.2.3 on 2023-07-07 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_category_manuscripts_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 3, 0, 11, 616639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='file_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.manuscripts'),
        ),
    ]
