# Generated by Django 4.2.3 on 2023-07-07 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_manuscripts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 3, 1, 59, 753648, tzinfo=datetime.timezone.utc)),
        ),
    ]
