# Generated by Django 4.2.3 on 2023-07-07 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_manuscripts_upload_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitors',
            old_name='file_name',
            new_name='filename',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 3, 14, 4, 44838, tzinfo=datetime.timezone.utc)),
        ),
    ]
