# Generated by Django 4.2.3 on 2023-07-07 23:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_file_name_visitors_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 23, 35, 36, 591910, tzinfo=datetime.timezone.utc)),
        ),
    ]
