# Generated by Django 4.2.5 on 2023-10-08 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_manuscripts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 8, 0, 2, 33, 192387, tzinfo=datetime.timezone.utc)),
        ),
    ]
