# Generated by Django 4.2.5 on 2023-11-03 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_manuscripts_upload_date_currentstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstudent',
            name='name',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 0, 6, 29, 85499, tzinfo=datetime.timezone.utc)),
        ),
    ]
