# Generated by Django 4.2.5 on 2023-11-03 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_currentstudent_role_alter_manuscripts_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 7, 59, 59, 727701, tzinfo=datetime.timezone.utc)),
        ),
    ]
