# Generated by Django 4.2.5 on 2023-11-04 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_pagevisit_delete_visitorcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 4, 8, 28, 15, 78954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='visited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 8, 28, 15, 78954, tzinfo=datetime.timezone.utc)),
        ),
    ]
