# Generated by Django 4.2.5 on 2023-11-05 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_alter_manuscripts_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 2, 7, 8, 594359, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pagevisit',
            name='visited_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 5, 2, 7, 8, 594359, tzinfo=datetime.timezone.utc)),
        ),
    ]
