# Generated by Django 4.2.5 on 2023-11-05 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_manuscripts_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagevisit',
            name='role',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 3, 2, 41, 137774, tzinfo=datetime.timezone.utc)),
        ),
    ]
