# Generated by Django 4.2.5 on 2023-11-05 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_pagevisit_role_alter_manuscripts_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagevisit',
            name='role',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 3, 15, 49, 97194, tzinfo=datetime.timezone.utc)),
        ),
    ]
