# Generated by Django 4.2.5 on 2023-11-05 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_currentstudent_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentstudent',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 4, 3, 44, 55314, tzinfo=datetime.timezone.utc)),
        ),
    ]
