# Generated by Django 4.2.5 on 2023-11-05 04:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_currentstudent_role_remove_staff_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='role',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='role',
        ),
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 4, 43, 22, 368527, tzinfo=datetime.timezone.utc)),
        ),
    ]
