# Generated by Django 4.2.5 on 2023-11-05 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_alumni_role_remove_faculty_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscripts',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 5, 8, 5, 37, 407715, tzinfo=datetime.timezone.utc)),
        ),
    ]
